version: "3.0"
services:
  nginx:
    build:
      # so that we can copy frontend/build to nginx
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      # -443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      # gives some time to postgres
      - postgres
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    ports:
      - '127.0.0.1:5432:5432'
    # restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    # where to find Dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    command: gunicorn backend.wsgi --bind 0.0.0.0:3031 --workers 4 --threads 4
    environment:
      # Postgres
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
      - POSTGRES_HOST=postgres
      - POSTGRES_TEST_DB=django_test
      # Superuser
      - SUPERUSER_USERNAME=Admin
      - SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SETTINGS_MODULE=backend.settings-prod
    ports:
      - "3031:3031"
    depends_on:
      - postgres
      - nginx
    tty: true
    volumes:
      # - ./backend/static:/backend/static:ro
      # # allow to call ./prod init_in_docker (bash script) from inside container
      - ./prod:/backend/prod:ro
      # - ./backend/backups:/backend/backups:Z
      # - ./backend/logs:/backend/logs:z

volumes:
  database:

# fix for: ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
# happens sometimes when your laptop vpn services use same addresses as docker network
# if this creates any type of error, just comment out everything. It will still work with the default network & default id addresses
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24